{
 "title": "Muxprom",
 "description": "gorilla/mux prometheus dashboard",
 "tags": [
  "gorilla/mux",
  "muxprom",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(muxprom_http_requests_inflight, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Last start date/time",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=\"$instance\"} * 1000"
    }
   ]
  },
  {
   "title": "Сurrent in-flight",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(muxprom_http_requests_inflight{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "RT Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(muxprom_http_request_duration_seconds_bucket[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Response size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(muxprom_http_response_size_sum{instance=\"$instance\"}[1m]) / rate(muxprom_http_response_size_count{instance=\"$instance\"}[1m])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Response time / Requests count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(muxprom_http_request_duration_seconds_sum{instance=\"$instance\"}[1m]) / rate(muxprom_http_request_duration_seconds_count{instance=\"$instance\"}[1m])",
     "legendFormat": "rt {{route}}"
    },
    {
     "expr": "rate(muxprom_http_request_duration_seconds_count{instance=\"$instance\"}[1m])",
     "legendFormat": "cnt {{route}}"
    }
   ]
  }
 ]
}